name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build Discord RSS Docker Image
      run: docker build -t discord-rss:automated_build_$(date +%s) .