name: Ubuntu 20.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Go Binary
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Golang Environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build Go Binary
      run: cd discord-rss && go build -v