name: Windows Server 2022 | Build Go Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Golang Environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build Go Binary
      run: cd discord-rss && go build -v